### ISSUE TITLE
No error handling implemented

### ISSUE THREAD

**Issue by rzetterberg** [spantaleev/ckeditor-imagebrowser#3]
The plugin does not show any kind of error handling at all. It just says "Loading ..."
Here are two common errors that is unhandled / supressed:
- A faulty URL is supplied for the JSON list
- A valid URL for the JSON list which responds with invalid JSON

This should at least throw an exception, and very best print an error message in the console. Otherwise it is hard to debug the problem.

**Comment by spantaleev** [comment]
Resolved by #5
